config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/faq'

  devise_for :users
  resources :gigs do
    resources :proposals, except: :index
    collection do
      get "search"
    end
  end

  resources :users do
    get :profile, on: :collection
    post :edit_profile, on: :collection
  end

  #render "welcome/about"
  #root "gigs#index"
  root "welcome#about"

  get "mygigs" => "gigs#mygigs"

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  belongs_to :gig
  belongs_to :skill
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :gigs

end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
end

app/models/gig.rb
class Gig < ActiveRecord::Base
  belongs_to :user
  has_many :proposals
  has_many :abilities
  has_many :skills, through: :abilities
  belongs_to :category

  geocoded_by :location
  after_validation :geocode

  def self.search(params)
    if params[:category].present?
      gigs = Gig.where(category_id: params[:category].to_i)
      gigs = gigs.where("name like ? or description like?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
      gigs = gigs.near(params[:location], 20) if params[:location].present?
    else
      gigs = Gig.where("name like ? or description like?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    end
    gigs
  end

  def skill_list=(skills_string)
    skill_names = skills_string.split(",").collect { |s| s.strip.downcase }.uniq
    new_or_found_skills = skill_names.collect { |name| Skill.find_or_create_by(name: name) }
    self.skills = new_or_found_skills
  end

  def skill_list
    self.skills.collect do |skill|
      skill.name
    end.join(", ")
  end

  def self.order_list(sort_order)
    if sort_order == "newest" || sort_order.blank?
      order(created_at: :desc)
    elsif sort_order == "name"
      order(name: :asc)
    else
      order(created_at: :asc)
    end
  end
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :gig
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :gigs
  has_many :proposals
  has_many :educations
  has_many :user_skills
  mount_uploader :avatar, AvatarUploader
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pundit
  protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :rails_admin

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # def rails_admin
  #   binding.pry
  # end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search, :show]

  def index
    if !params[:skill_jobs]
      @gigs = Gig.all.order_list(params[:sort_by]).page(params[:page]).per(12)
    else
      @gigs = Gig.joins(:skills).where(skills: {name: current_user.user_skills.pluck(:skill)}).order_list(params[:sort_by]).page(params[:page]).per(12)
    end
    @users = User.all
  end

  def show
    @gig = Gig.find(params[:id])
    @proposals = @gig.proposals.order("created_at DESC").joins(:user)
    @awarded_proposal = Proposal.where(id: @gig.awarded_proposal).first
    #@awarded_proposal = @gig.proposals.order("created_at DESC").joins(:users).joins(:gigs).where(gig_id: params[:id])
  end

  def new
    @gig = Gig.new
  end

  def create
    @gig = Gig.new(gig_params)
    @gig.user = current_user
    if @gig.save
      User.all.each do |user|
        NewGigMailer.send_mail(user).deliver
      end
      redirect_to @gig
    else
      flash[:error] = @gig.errors.full_messages.to_sentence
      render "new"
    end
  end

  def edit
    @gig = Gig.find(params[:id])
    if current_user != @gig.user
      flash[:error] = "You are not the owner of this gig"
      redirect_to @gig
    end
  end

  def update
    @gig = Gig.find(params[:id])
    if current_user == @gig.user
      @gig.update(gig_params)
    else
      flash[:error] = "You are not the owner of this gig"
    end
    redirect_to @gig

  end

  def destroy
    @gig = Gig.find(params[:id])
    if current_user == @gig.user
      @gig.destroy
    else
      flash[:error] = "You are not the owner of this gig"
    end
    redirect_to :mygigs
  end

  def search
    if params[:category].blank? && params[:search].blank?
      @gigs = Gig.all.order("created_at desc").page(params[:page]).per(12)
    else
      @gigs = Gig.search(params).page(params[:page]).per(12)
    end
  end

  def mygigs
    @gigs = Gig.where(user_id: current_user).order("created_at desc")
  end

  private
    def gig_params
      params.require(:gig).permit(:name, :location, :description, :budget, :category_id, :skill_list, :awarded_proposal)
    end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  def create
    @gig = Gig.find(params[:gig_id])
    @proposal = @gig.proposals.create(proposal_params)
    @proposal.update(user_id: current_user.id)
    redirect_to @proposal.gig
  end

  private
    def proposal_params
      params.require(:proposal).permit(:bid, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
  end
  
  def edit_profile
    if params[:profile].present?
      current_user.update(avatar: params[:profile][:avatar]) if params[:profile][:avatar].present?
      current_user.update(about: params[:profile][:about]) if params[:profile][:about].present?
    end
    if params[:education].present?
      if !params[:education][:id].present?
        current_user.educations.create(institure_name: params[:education][:institure_name], description: params[:education][:description])
      else
        Education.find(params[:education][:id]).update(institure_name: params[:education][:institure_name], description: params[:education][:description])
      end
    end
    if params[:user_skills].present?
      skils_array = params[:user_skills][:skill].split(",")
      current_user.user_skills.destroy_all
      skils_array.each do |user_skill|
        current_user.user_skills.create(skill: user_skill)
      end
    end
    redirect_to profile_users_path, notice: "profile updated"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def contact
  end

  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gigs/_gig_form.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDaMIwD-73f2_FuvWcAm0olLBYwMTkR9os&libraries=places"></script>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= simple_form_for @gig do |f| %>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.input :name, class: "form-control"%>
          </div>
          <div class="form-group">
            <%= f.label :category_id %> 

            <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), {}, class: "form-control input-lg" %>
                      </div>
          <div class="form-group">
            <%= f.input :location, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.input :description, input_html: { row: 20 }, class: "form-control" %>
          </div>
          <legend>List Skills required for this job.</legend>
          <div class="form-group">
            <!-- <%= f.text_area :skill_list, rows: 3, class: "form-control" %> -->
            <%= f.select :skill_list, options_from_collection_for_select(Skill.all, :name, :name), {}, class: "form-control input-lg" %>
                      </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.input :budget, class: "form-control"%>
          </div>
          <%= f.submit "CREATE JOB",class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/gigs/edit.html.erb
<%= render "gig_form" %>

app/views/gigs/index.html.erb
<div class="container">
  <h1>We currently have <strong><%= @gigs.total_count %></strong> jobs from <strong><%= @users.count %></strong> Job Providers</h1>
  <%= form_tag search_gigs_path, method: :get do |f| %>
    <%= text_field_tag :search, nil, placeholder: "Example Software Developer", class: "col-md-9 input-lg" %>
    <%= submit_tag "Search", class: "col-md-3 btn2 btn-primary input-lg" %>
  <% end %>
</div>

<%= render "layouts/gig_listings" %>

app/views/gigs/mygigs.html.erb
<div class="container">
  <h3>My Gigs <small class="pull-right"><%= @gigs.count %> total</small></h3>
  <table class="table">
    <thead>
      <tr>
        <th class="text-center">Status</th>
        <th>Name</th>
        <th>Category</th>
        <th>Budget</th>
        <th class="text-center">Proposals</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @gigs.each do |gig| %>
        <tr>
          <td>
            <% if gig.open %>
              open
            <% else %>
              close
            <% end %>
          </td>
          <td>
            <%= link_to gig.name, gig %>
          </td>
          <td>
            <%= gig.category.name if gig.category %>
          </td>
          <td>
            <%= number_to_currency(gig.budget, precision: 0) %>
          </td>
          <td>
            <%= gig.proposals.count %>
          </td>
          <td><%= link_to "Edit", edit_gig_path(gig), class: "text-warning" %></td>
          <td><%= link_to "Delete", gig_path(gig), method: :delete, data: { confirm: "Are you sure?" }, class: "text-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/gigs/search.html.erb
<div class="container">
  <h1>Your search resulted in | <strong><%= @gigs.total_count %></strong> gigs.</h1>
  <%= form_tag search_gigs_path, method: :get do |f| %>
    <%= text_field_tag :search, nil, placeholder: "Example Software Developer", class: "col-md-9" %>
    <%= submit_tag "Search", class: "col-md-3 btn2 btn-primary" %>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-3">
      <h3 class="">Advanced search</h3>
      <%= form_tag search_gigs_path, method: :get do |f| %>
        <div class="form-group">
          <label>Search</label>
          <%= text_field_tag :search, nil, placeholder: "Developer, Accountant, etc.", class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label>Category</label>
          <%= select_tag :category, options_from_collection_for_select(Category.all, :id, :name), class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label>Location</label>
          <%= text_field_tag :location, nil, placeholder: "Georgetown, Penang, etc", class: "form-control input-lg" %>
        </div>
        <br>
        <%= submit_tag "Search", class: "btn btn-primary btn-block input-lg" %>
      <% end %>
    </div>
    <div class="col-xs-12 col-md-9">
      <h3>Gigs
        <span class="pull-right"><small>1 - 12 results</small></span>
      </h3>    
          <div class="pull-right">
          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Sort by
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to "Oldest", gigs_path(sort_by: "oldest") %></li>
              <li><%= link_to "Newest", gigs_path(sort_by: "newest") %></li>
              <li><%= link_to "Name", gigs_path(sort_by: "name") %></li>
            </ul>
          </div>
        </div>
      <table class="table table-striped" style="background-color: rgb(89, 158, 243);" >
        <tbody>
          <% @gigs.each do |gig| %>
          <tr>
            <td>
              <p>
                <%= link_to gig.name, gig %>
               
              </p>
              <p>Google enterprises</p>
            </td>
            <td>
              <p><i class="glyphicon glyphicon-calendar"><%= gig.created_at.strftime("%b %d, %Y") %></i></p>
              <p><i class="glyphicon glyphicon-map-marker"></i><%= gig.location %></p>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="text-center">
      <%= paginate @gigs %>
    </div>
  </div>
</div>

app/views/gigs/show.html.erb
<div class="container">
  <div class="row">
    <h2>Job detail
      <span class="pull-right">
        <small><%= link_to "&larr; All Jobs".html_safe, search_gigs_path %></small>
      </span>
    </h2>
    <div class="col-xs-12 col-md-8"  style="background: white;padding: 40px;">
      <h3><%= @gig.name %></h3>
      <p><i class="glyphicon glyphicon-calendar"></i> <%= @gig.created_at.strftime("%b %d, %Y") %> | <i class="glyphicon glyphicon-map-marker"></i> <%= @gig.location %> | <span class="label label-success"><%= number_to_currency(@gig.budget, precision: 0) %></span></p>
      <br>
      <h2 style="margin-top: -24px;">Description</h2>
      <div class="ui divider"></div>
      <p><%= @gig.description %></p>
      <h2>Skills Wanted</h2>
      <div class="ui divider"></div>
      <ul>
        <% @gig.skills.each do |skill| %>
          <li><%= skill.name %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-xs-12 col-md-4">
      <h2>Submit a Proposal</h2>
      <div class="ui divider"></div>
      <% if user_signed_in? && @gig.user != current_user %>
        <%= form_for :proposal, url: gig_proposals_path(@gig) do |f| %>
        <div class="row">
          <div class="col-xs-12 col-md-12">
            <div class="form-group">
              <%= f.label :bid %>
              <%= f.text_field :bid, class: "form-control input-lg" %>
              <small class="help-block">Amount of your bid.</small>
            </div>
          </div>
          <div class="col-xs-12 col-md-12">
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, rows: 5, class: "form-control input-lg" %>
              <small class="help-block">Explain the skills needed for this gig.</small>
            </div>
          </div>
        </div>
        <br>
        <%= f.submit "Submit Proposal", class: "btn btn-primary input-lg" %>
        <% end %>
      <% elsif @gig.user == current_user && @gig.open == true %>
        <h3 class="text-center">You can't bid on your own Job!</h3>
      <% elsif @gig.open == false %>
        <h3 class="text-center">This Job is closed!</h3>
      <% else %>
        <h3 class="text-center">Sign in to make a bid!</h3>
        <%= link_to "Log in", new_user_session_path, class: "btn btn-primary btn-lg" %>
      <% end %>

    </div>

      <% if @awarded_proposal.present? %>
        <div class="col-xs-12 col-md-8">
          <h3>Awarded_proposal</h3>
          <div class="panel panel-default">
            <div class="panel-heading">
              <div class="row">
                <div class="col-md-4">
                  <h3 class="panel-title"><%= @awarded_proposal.user_id  if @awarded_proposal.user %></h3>  
                </div>
                  <div class="col-md-4">
                  <h3 class="panel-title">
                    Bid: <%= number_to_currency(@awarded_proposal.bid, precision: 0) %>
                  </h3>
                </div>
                <div class="col-md-4">
                  <h3 class="panel-title">
                    Posted: <%= @awarded_proposal.created_at.strftime("%B %d, %Y") %>
                  </h3>
                </div>
              </div>
            </div>
            <div class="panel-body">
              <%= @awarded_proposal.description %>
            </div>
          </div>
        </div>
      <% end %>

      <% if @proposals.present? %>
        <div class="col-xs-12 col-md-8">
          <h3>Proposals</h3>
            <% @proposals.each do |proposal| %>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <div class="row">
                    <div class="col-md-4">
                      <h3 class="panel-title"><%= proposal.user.name %></h3>
                    </div>
                    <div class="col-md-4">
                      <h3 class="panel-title">
                        Bid: <%= number_to_currency(proposal.bid, precision: 0) %>
                      </h3>
                    </div>
                    <div class="col-md-4">
                      <h3 class="panel-title">
                        Posted: <%= proposal.created_at.strftime("%b %d, %Y") %>
                      </h3>
                    </div>
                  </div>
                </div>
                <div class="panel-body">
                  <%= proposal.description %>
                </div>
                <% if current_user == @gig.user && @gig.awarded_proposal.blank? %>
                  <div class="panel-footer">
                    <%= simple_form_for @gig, method: :put do |f| %>
                      <%= f.input :awarded_proposal, as: :hidden, input_html: { value: proposal.id } %>
                      <%= f.input :open, as: :hidden, input_html: { value: false } %>
                      <%= f.submit "Award Proposal", class: "btn btn-success" %>
                    <% end %>
                  </div>
                <% end %>

              </div>
            <% end %>
          <% else %>
          <% end %>
      </div>
  </div>
</div>

app/views/layouts/_gig_listings.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-3">
      <h3 class="">Advanced search</h3>
      <%= form_tag search_gigs_path, method: :get do |f| %>
        <div class="form-group">
          <label>Search</label>
          <%= text_field_tag :search, nil, placeholder: "Developer, Accountant, etc.", class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label>Category</label>
          <%= select_tag :category, options_from_collection_for_select(Category.all, :id, :name), class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label>Location</label>
          <%= text_field_tag :location, nil, placeholder: "Georgetown, Penang, etc", class: "form-control input-lg" %>
        </div>
        <br>
        <%= submit_tag "Search", class: "btn btn-primary btn-block input-lg" %>
      <% end %>
    </div>
    <div class="col-xs-12 col-md-9">
      <h3>Jobs
        <div class="pull-right">
          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Sort by
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to "Oldest", gigs_path(sort_by: "oldest") %></li>
              <li><%= link_to "Newest", gigs_path(sort_by: "newest") %></li>
              <li><%= link_to "Name", gigs_path(sort_by: "name") %></li>
            </ul>
          </div>
        </div>
      </h3>
      <table class="table table-striped" >
        <tbody>
          <% @gigs.each do |gig| %>
          <tr>
            <td class="col-md-6">
              <p>
                <%= link_to gig.name, gig %>
                <small class="label label-success"><%= number_to_currency(gig.budget, precision: 0) %></small>
              </p>
              <p><%= h truncate(gig.description, length: 500) %></p>
              <p>Skills: <%= gig.skills.map { |s| s.name }.join(", ") %></p>
            </td>
            <td>
              <%= gig.category.name if gig.category %>
            </td>
            <td>
              <p><i class="fa fa-calendar"> <%= gig.created_at.strftime("%b %d, %Y")%></i></p>
              <p><i class="fa fa-map-marker"></i> <%= gig.location %></p>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="text-center">
      <%= paginate @gigs %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Sapot Member", gigs_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <div class="navbar-left">
      <%= link_to "Post a Job &raquo;".html_safe, new_gig_path, class: "btn btn-primary navbar-btn" %>
      <%= link_to "Search you skills related job", gigs_path(skill_jobs: true), class: "btn btn-primary navbar-btn" %>
      </div>

      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "How it Works",welcome_about_path, class: "btn navbar-btn" %></li>
        
     
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", profile_users_path %></li>
              <li><%= link_to "My Job", mygigs_path %></li>
              <li><%= link_to "settings", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path, class: "btn btn-success navbar-btn" %></li>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info navbar-btn" %></li>
        <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/profile.html.slim
.profile
  .profile_div style="padding: 36px;color:white;"
    -if current_user.admin == true
      = link_to "Admin Page", rails_admin_path, class: "ui teal button", style:"float:right;", target: :_blank
    h1 Profile
    = form_for(:profile, url: edit_profile_users_path, method: :post, html: { autocomplete: "off" }) do |f|
      .avatar_uploader_block
        -if current_user.avatar.present?
          = image_tag current_user.avatar, class: 'profile_avatar'
        -else
          = image_tag image_url('default-img.png'), class: 'profile_avatar'
      br
      = f.file_field :avatar
      h1 About
      -if current_user.about.present?
        = f.text_area :about, value: current_user.about,placeholder:"Tell us about yourself", style: "width: 100%;height: 100px;padding: 16px;"
      -else
        = f.text_area :about,placeholder:"Tell us about yourself", style: "width: 100%;height: 100px;padding: 16px;"
      = f.submit "Save Profile", class: "ui primary button", style: "float: right;background: #f15f41;"
    br
    br
    .white_div
      h4 
        |Education
        = link_to "Add Education", "#", class: "ui button education_edit", id: "education"
      -if current_user.educations.present?
        -current_user.educations.each do |education|
          .sub_div style="padding: 16px 27px 17px 27px;border: 1px solid rgba(128, 128, 128, 0.37);margin-top: 25px;"
            .education_details id="education_details#{education.id}"
              h4
                = education.institure_name
                i.edit.icon style="float:right;font-size:30px;color:gray;" id="#{education.id}"
              p style="margin-top: -15px;" = education.description
            .edit_education_details.hide id="edit_education_details#{education.id}"
              = form_for(:education, url: edit_profile_users_path, method: :post, html: { autocomplete: "off" }) do |f|
                = f.hidden_field :id, value: education.id
                = f.text_field :institure_name, value: education.institure_name,required: true, style: "width: 100%;height: 46px;padding: 16px;margin-bottom: 27px;margin-top: 14px;"
                = f.text_area :description, value:  education.description, required: true, style: "width: 100%;height: 100px;padding: 16px;"
                br
                br
                =f.submit "Save", class: "ui primary button", style: "float:right;background: #f15f41;"
                =link_to "Cancel", "", class: "ui primary button", style: "float:right;background: gray;"
                br
                br
    .white_div
      h4 
        |Skills
        = link_to "Add Skills", "#", class: "ui button education_edit", id: "user_skill"
      br
      -if current_user.user_skills.present?
        -current_user.user_skills.each do |user_skill|
          .button.ui.primary.gray.basic.button
            = user_skill.skill
          br
          br

  .ui.small.modal.education style="text-align: center;padding: 55px;height: 394px;"
    h3 Add Education
    = form_for(:education, url: edit_profile_users_path, method: :post, html: { autocomplete: "off" }) do |f|
      = f.text_field :institure_name, placeholder: "Name of Institute",required: true, style: "width: 100%;height: 46px;padding: 16px;margin-bottom: 27px;margin-top: 14px;"
      = f.text_area :description, placeholder: "About Institute", required: true, style: "width: 100%;height: 100px;padding: 16px;"
      br
      br
      = f.submit "Save", class: "ui primary button", style: "float: right;background: #f15f41;"

  .ui.small.modal.skills style="text-align: center;padding: 55px;height: 394px;"
    h3 Select Skills
    -value = ""
    -if Skill.all.present?
      -Skill.all.each do |skill|
        -if current_user.user_skills.find_by(skill: skill.name).present?
          -style = "background: #f25f42 !important;color: white !important;"
          -value += "#{skill.name},"
        .button.ui.primary.gray.basic.button id="#{skill.name}" style="margin-bottom: 16px;margin-right: 20px;#{style}"
          = skill.name
      = form_for(:user_skills, url: edit_profile_users_path, method: :post, html: { autocomplete: "off" }) do |f|
        = f.hidden_field :skill, placeholder: "About Institute", value: value, required: true, style: "width: 100%;height: 100px;padding: 16px;"
        br
        br
        = f.submit "Save", class: "ui primary button", style: "float: right;background: #f15f41;"
        =link_to "Cancel", "", class: "ui primary button", style: "float:right;background: gray;"

javascript:
  $('#education').on('click', function(evt) {
    $(".ui.small.modal.education").modal('show');
    return evt.preventDefault();
  });
  $('.edit.icon').on('click', function(evt) {
    document.getElementById('education_details' + evt.target.id).className = "education_details hide"
    document.getElementById('edit_education_details' + evt.target.id).className = "edit_education_details"
  });
  $('.button.ui.primary.gray.basic.button').on('click', function(evt) {
    if (evt.target.style.background !== "rgb(242, 95, 66)"){
      evt.target.style = "background: #f25f42 !important;color: white !important;";
      if (document.getElementById('user_skills_skill').value !== ""){
        document.getElementById('user_skills_skill').value += "," + evt.target.id;
      }else{
        document.getElementById('user_skills_skill').value += evt.target.id;
      };
    }else{
      evt.target.style = "background: transparent !important;color:#1678c2 !important";
      debugger
      var skill_array = document.getElementById('user_skills_skill').value.split(",")
      var new_array = $(skill_array).not([evt.target.id]).get();
      document.getElementById('user_skills_skill').value = new_array;
    };
  });
  $('#user_skill').on('click', function(evt) {
    $(".ui.small.modal.skills").modal('show');
    return evt.preventDefault();
  });